### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by loevgaard** [graze/console-diff-renderer#13]
Hi

Can you release a new version of this library. Your master supports Symfony 4, but your latest tag doesn't :)

Thanks in advance.

**Comment by biggianteye** [comment]
Out of curiosity, what are you using it for?

**Comment by h-bragg** [comment]
Done: https://github.com/graze/console-diff-renderer/releases/tag/0.6.2

**Comment by loevgaard** [comment]
Thank you. I use your parallel processing library which requires this :)
